name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk
          python3 -m pip install --upgrade pip
          pip install buildozer cython
          sudo apt install -y git zip unzip \
            automake autoconf libtool pkg-config \
            libncurses5 libncurses5-dev \
            libstdc++6 libffi-dev \
            libssl-dev libsqlite3-dev

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer init
          cp main.py .
          echo "[app]
